// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1D3JE3RWgqXChSpJbYUsB8z990_vxrME',
    appId: '1:1077572684685:web:2f03eb8206a706e7b24bc4',
    messagingSenderId: '1077572684685',
    projectId: 'finalsmart-8a718',
    authDomain: 'finalsmart-8a718.firebaseapp.com',
    storageBucket: 'finalsmart-8a718.firebasestorage.app',
    measurementId: 'G-BH8MX68PVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0_w8CoVxtS-ZOlP-Y7wiQY4b8SXItBtA',
    appId: '1:1077572684685:android:ca4c6e7c327308e2b24bc4',
    messagingSenderId: '1077572684685',
    projectId: 'finalsmart-8a718',
    storageBucket: 'finalsmart-8a718.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDStHRie2LXOLAxz_8mRrVAOIKXHKY6VcY',
    appId: '1:1077572684685:ios:355c0f9fff1e8ea3b24bc4',
    messagingSenderId: '1077572684685',
    projectId: 'finalsmart-8a718',
    storageBucket: 'finalsmart-8a718.firebasestorage.app',
    iosBundleId: 'com.example.finalPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDStHRie2LXOLAxz_8mRrVAOIKXHKY6VcY',
    appId: '1:1077572684685:ios:355c0f9fff1e8ea3b24bc4',
    messagingSenderId: '1077572684685',
    projectId: 'finalsmart-8a718',
    storageBucket: 'finalsmart-8a718.firebasestorage.app',
    iosBundleId: 'com.example.finalPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1D3JE3RWgqXChSpJbYUsB8z990_vxrME',
    appId: '1:1077572684685:web:757540e20a8b6446b24bc4',
    messagingSenderId: '1077572684685',
    projectId: 'finalsmart-8a718',
    authDomain: 'finalsmart-8a718.firebaseapp.com',
    storageBucket: 'finalsmart-8a718.firebasestorage.app',
    measurementId: 'G-W8754HFGB4',
  );
}
